### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by forart** [Barabas5532/TubeScreamer#2]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [AUDIO category](https://github.com/forart/HyMPS#- ) \ [Effects page](https://github.com/forart/HyMPS/blob/main/Audio/Effects.md#-- ) \ [Guitar section](https://github.com/forart/HyMPS/blob/main/Audio/Guitar.md#--- ) \ [Pedals subsection](https://github.com/forart/HyMPS/blob/main/Audio/GPedals.md#---- ) \ [Overdrive](https://github.com/forart/HyMPS/blob/main/Audio/GPedals.md#overdrive-)), can you please add a GH-compliant license file for it ?

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/Barabas5532/TubeScreamer/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/Barabas5532/TubeScreamer/?label=LICENSE)

Anyway you can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by MarcoRavich** [comment]
Thanks, works now.
